
```{r}

library(rvest)
library(dplyr)
library(ggplot2)

comp_name <- "prudential-life-insurance-assessment"

url_board <- paste0("https://www.kaggle.com/c/",comp_name,"/leaderboard/")

d1 <- read_html(paste0(url_board,"public")) %>% 
   html_node("table") %>% html_table() %>% select(c(1,3,4)) %>% tbl_df
names(d1) <- c("r1","name1","s1")  
d1 <- d1 %>% mutate(name1 = sub("\r.*","",name1)) 

d2 <- read_html(paste0(url_board,"private")) %>% 
   html_node("table") %>% html_table() %>% select(1:5) %>% tbl_df
names(d2) <- c("r2","dr","name2","s2","entries")  
d2 <- d2 %>% mutate(dr = as.numeric(sub("↓","-",sub("↑","",dr))), 
                r1 = r2 + dr, name2 = sub("\r.*","",name2)) 

```

```{r}

nrow(d1)
nrow(d2)

d1 %>% filter(is.na(r1))
d2 %>% filter(is.na(r1)) %>% as.data.frame

d <- inner_join(d1, d2, by = "r1")
nrow(d)

d %>% filter(name1!=name2) %>% nrow

```

```{r}

ggplot(d) + geom_point(aes(x = s1, y = s2))

ggplot(d) + geom_histogram(aes(x = s2))
ggplot(d) + geom_histogram(aes(x = s2)) + xlim(c(0.6,0.7))
ggplot(d) + geom_histogram(aes(x = s2)) + xlim(c(0.66,0.68))
ggplot(d) + geom_histogram(aes(x = s2)) + xlim(c(0.667,0.669))
d %>% filter(s2>0.668, s2<0.6685) %>% nrow

ggplot(d) + geom_point(aes(x = s1, y = s2)) + 
  xlim(c(0.6,0.7)) + ylim(c(0.6,0.7)) + geom_abline()
ggplot(d) + geom_point(aes(x = s1, y = s2)) + 
  xlim(c(0.66,0.685)) + ylim(c(0.66,0.685)) + geom_abline()
ggplot(d) + geom_point(aes(x = s1, y = s2)) + 
  xlim(c(0.67,0.68)) + ylim(c(0.665,0.68)) + geom_abline()

```

```{r}

d %>% filter(name1=="salacika")

d %>% mutate(grp = ifelse(r2<=3,"priv LB top3",
  ifelse(r1<=3,"pub LB top3",ifelse(name1=="salacika","my student","")))) %>% 
  ggplot() + geom_point(aes(x = s1, y = s2, color = grp), alpha = 0.5) + 
    xlim(c(0.66,0.685)) + ylim(c(0.66,0.685)) + geom_abline(color = "grey20") +
    scale_color_manual(values = c("grey30","blue","#1A9900","red")) +
    annotate("segment", x = 0.669, xend = 0.671, y = 0.673, yend = 0.671,
        colour="blue", size=1, arrow=arrow(length = unit(0.03,"npc"))) +
    coord_fixed(ratio = 1) + xlab("score - pub LB") + ylab("score - priv LB")
  
```

```{r}

d %>% filter(s1>0.665, s2>0.665) %>% nrow

d %>% filter(s1>0.665, s2>0.665) %>% 
   ggplot() + geom_point(aes(x = s1, y = s2, size = entries), alpha = 0.3)

d %>% filter(s1>0.665, s2>0.665) %>% 
   ggplot() + geom_point(aes(x = entries, y = s2-s1), alpha = 0.3) 


```








